import pandas as pd

# 주요 개 품종 영-한 매핑 딕셔너리 생성
breed_mapping = {
    'affenpinscher': '아펜핀셔',
    'afghan-hound': '아프간 하운드',
    'airedale-terrier': '에어데일 테리어',
    'akita': '아키타',
    'alaskan-klee-kai': '알래스칸 클리 카이',
    'alaskan-malamute': '알래스칸 말라뮤트',
    'american-bulldog': '아메리칸 불독',
    'american-english-coonhound': '아메리칸 잉글리시 쿤하운드',
    'american-eskimo-dog': '아메리칸 에스키모 도그',
    'american-foxhound': '아메리칸 폭스하운드',
    'american-hairless-terrier': '아메리칸 헤어리스 테리어',
    'american-leopard-hound': '아메리칸 레오파드 하운드',
    'american-staffordshire-terrier': '아메리칸 스태퍼드셔 테리어',
    'american-water-spaniel': '아메리칸 워터 스파니엘',
    'anatolian-shepherd-dog': '아나톨리안 셰퍼드 도그',
    'appenzeller-sennenhund': '아펜첼러 센넨훈트',
    'australian-cattle-dog': '오스트레일리안 캐틀 도그',
    'australian-kelpie': '오스트레일리안 켈피',
    'australian-shepherd': '오스트레일리안 셰퍼드',
    'australian-stumpy-tail-cattle-dog': '오스트레일리안 스텀피 테일 캐틀 도그',
    'australian-terrier': '오스트레일리안 테리어',
    'azawakh': '아자와크',
    'barbado-da-terceira': '바르바도 다 테르세이라',
    'barbet': '바비트',
    'basenji': '바센지',
    'basset-fauve-de-bretagne': '바셋 포브 드 브레타뉴',
    'basset-hound': '바셋 하운드',
    'bavarian-mountain-scent-hound': '바바리안 마운틴 센트 하운드',
    'beagle': '비글',
    'bearded-collie': '비어디드 콜리',
    'beauceron': '보세론',
    'bedlington-terrier': '베들링턴 테리어',
    'belgian-laekenois': '벨지안 레커노이즈',
    'belgian-malinois': '벨지안 말리노이즈',
    'belgian-sheepdog': '벨지안 쉽독',
    'belgian-tervuren': '벨지안 터뷰런',
    'bergamasco-sheepdog': '베르가마스코 쉽독',
    'berger-picard': '베르제 피카르',
    'bernese-mountain-dog': '버니즈 마운틴 독',
    'bichon-frise': '비숑 프리제',
    'biewer-terrier': '비웨어 테리어',
    'black-and-tan-coonhound': '블랙 앤 탄 쿤하운드',
    'black-russian-terrier': '블랙 러시안 테리어',
    'bloodhound': '블러드하운드',
    'blue-picardy-spaniel': '블루 피카디 스파니엘',
    'bluetick-coonhound': '블루틱 쿤하운드',
    'boerboel': '보어볼',
    'bohemian-shepherd': '보헤미안 셰퍼드',
    'bolognese': '볼로네즈',
    'border-collie': '보더 콜리',
    'border-terrier': '보더 테리어',
    'borzoi': '보르조이',
    'boston-terrier': '보스턴 테리어',
    'bouvier-de-ardennes': '부비에 데 아르덴',
    'bouvier-des-flandres': '부비에 데 플랑드르',
    'boxer': '복서',
    'boykin-spaniel': '보이킨 스파니엘',
    'bracco-italiano': '브라코 이탈리아노',
    'braque-du-bourbonnais': '브라크 뒤 부르보네',
    'braque-francais-pyrenean': '브라크 프랑세 피레니안',
    'braque-saint-germain': '브라크 생 제르맹',
    'brazilian-terrier': '브라질리안 테리어',
    'briard': '브리아드',
    'brittany': '브리타니',
    'broholmer': '브로홀머',
    'brussels-griffon': '브뤼셀 그리폰',
    'bull-terrier': '불 테리어',
    'bulldog': '불독',
    'bullmastiff': '불마스티프',
    'cairn-terrier': '케언 테리어',
    'calupoh': '칼루포',
    'canaan-dog': '카나안 도그',
    'canadian-eskimo-dog': '캐나디안 에스키모 도그',
    'cane-corso': '케인 코르소',
    'cardigan-welsh-corgi': '웰시 코기 카디건',
    'carolina-dog': '캐롤라이나 도그',
    'catahoula-leopard-dog': '카타울라 레오파드 도그',
    'caucasian-shepherd-dog': '코카시안 셰퍼드 도그',
    'cavalier-king-charles-spaniel': '캐벌리에 킹 찰스 스파니엘',
    'central-asian-shepherd-dog': '센트럴 아시안 셰퍼드 도그',
    'cesky-terrier': '체스키 테리어',
    'chesapeake-bay-retriever': '체서피크 베이 리트리버',
    'chihuahua': '치와와',
    'chinese-crested': '차이니즈 크레스티드',
    'chinese-shar-pei': '차이니즈 샤페이',
    'chinook': '치눅',
    'chow-chow': '차우차우',
    'cirneco-delletna': '치르네코 델레트나',
    'clumber-spaniel': '클럼버 스파니엘',
    'cocker-spaniel': '코카 스파니엘',
    'collie': '콜리',
    'coton-de-tulear': '코튼 드 튈레아',
    'croatian-sheepdog': '크로아티안 쉽독',
    'curly-coated-retriever': '컬리 코티드 리트리버',
    'czechoslovakian-vlciak': '체코슬로바키안 블치아크',
    'dachshund': '스탠다드 닥스훈트',
    'dalmatian': '달마시안',
    'dandie-dinmont-terrier': '댄디 딘몬트 테리어',
    'danish-swedish-farmdog': '대니시 스웨디시 팜독',
    'deutscher-wachtelhund': '도이처 바흐텔훈트',
    'doberman-pinscher': '도베르만 핀셔',
    'dogo-argentino': '도고 아르헨티노',
    'dogue-de-bordeaux': '도그 드 보르도',
    'drentsche-patrijshond': '드렌체 파트리즈혼트',
    'drever': '드레버',
    'dutch-shepherd': '더치 셰퍼드',
    'english-cocker-spaniel': '잉글리시 코커 스파니엘',
    'english-foxhound': '잉글리시 폭스하운드',
    'english-setter': '잉글리시 세터',
    'english-springer-spaniel': '잉글리시 스프링어 스파니엘',
    'english-toy-spaniel': '잉글리시 토이 스파니엘',
    'entlebucher-mountain-dog': '엔틀부처 마운틴 도그',
    'estrela-mountain-dog': '에스트렐라 마운틴 도그',
    'eurasier': '유라지어',
    'field-spaniel': '필드 스파니엘',
    'finnish-lapphund': '피니시 랩훈드',
    'finnish-spitz': '피니시 스피츠',
    'flat-coated-retriever': '플랫 코티드 리트리버',
    'french-bulldog': '프렌치 불독',
    'french-spaniel': '프렌치 스파니엘',
    'german-longhaired-pointer': '저먼 롱헤어드 포인터',
    'german-pinscher': '저먼 핀셔',
    'german-shepherd-dog': '저먼 셰퍼드',
    'german-shorthaired-pointer': '저먼 쇼트헤어드 포인터',
    'german-spitz': '저먼 스피츠',
    'german-wirehaired-pointer': '저먼 와이어헤어드 포인터',
    'giant-schnauzer': '자이언트 슈나우저',
    'glen-of-imaal-terrier': '글렌 오브 이말 테리어',
    'golden-retriever': '골든 리트리버',
    'gordon-setter': '고든 세터',
    'grand-basset-griffon-vendeen': '그랑 바셋 그리폰 방데앵',
    'great-dane': '그레이트 데인',
    'great-pyrenees': '그레이트 피레니즈',
    'greater-swiss-mountain-dog': '그레이터 스위스 마운틴 도그',
    'greyhound': '그레이하운드',
    'hamiltonstovare': '해밀턴스토바레',
    'hanoverian-scenthound': '하노베리안 센트하운드',
    'harrier': '해리어',
    'havanese': '하바니즈',
    'hokkaido': '홋카이도',
    'hovawart': '호바워트',
    'ibizan-hound': '이비잔 하운드',
    'icelandic-sheepdog': '아이슬란딕 쉽독',
    'irish-red-and-white-setter': '아이리시 레드 앤 화이트 세터',
    'irish-setter': '아이리시 세터',
    'irish-terrier': '아이리시 테리어',
    'irish-water-spaniel': '아이리시 워터 스파니엘',
    'irish-wolfhound': '아이리시 울프하운드',
    'italian-greyhound': '이탈리안 그레이하운드',
    'jagdterrier': '야크트테리어',
    'japanese-akitainu': '재패니즈 아키타이누',
    'japanese-chin': '재패니즈 친',
    'japanese-spitz': '재패니즈 스피츠',
    'japanese-terrier': '재패니즈 테리어',
    'kai-ken': '카이 켄',
    'karelian-bear-dog': '카렐리안 베어 도그',
    'keeshond': '키스혼드',
    'kerry-blue-terrier': '케리 블루 테리어',
    'kishu-ken': '키슈 켄',
    'komondor': '코몬도르',
    'korean-jindo-dog': '진도견',
    'kromfohrlander': '크롬포랜더',
    'kuvasz': '쿠바츠',
    'labrador-retriever': '라브라도 리트리버',
    'lagotto-romagnolo': '라고토 로마뇰로',
    'lakeland-terrier': '레이크랜드 테리어',
    'lancashire-heeler': '랭커셔 힐러',
    'lapponian-herder': '라포니안 허더',
    'large-munsterlander': '라지 뮌스터랜더',
    'leonberger': '레온베르거',
    'lhasa-apso': '라사 압소',
    'lowchen': '뢰첸',
    'maltese': '말티즈',
    'manchester-terrier-standard': '맨체스터 테리어 스탠다드',
    'manchester-terrier-toy': '맨체스터 테리어 토이',
    'mastiff': '마스티프',
    'miniature-american-shepherd': '미니어처 아메리칸 셰퍼드',
    'miniature-bull-terrier': '미니어처 불 테리어',
    'miniature-pinscher': '미니어처 핀셔',
    'miniature-schnauzer': '미니어처 슈나우저',
    'mountain-cur': '마운틴 커',
    'mudi': '무디',
    'neapolitan-mastiff': '네아폴리탄 마스티프',
    'nederlandse-kooikerhondje': '네덜란드세 코이커혼제',
    'newfoundland': '뉴펀들랜드',
    'norfolk-terrier': '노퍽 테리어',
    'norrbottenspets': '노르보텐스펫츠',
    'norwegian-buhund': '노르웨이안 부훈드',
    'norwegian-elkhound': '노르웨이안 엘크하운드',
    'norwegian-lundehund': '노르웨이안 룬데훈드',
    'norwich-terrier': '노리치 테리어',
    'nova-scotia-duck-tolling-retriever': '노바 스코샤 덕 톨링 리트리버',
    'old-english-sheepdog': '올드 잉글리시 쉽독',
    'otterhound': '오터하운드',
    'papillon': '파피용',
    'parson-russell-terrier': '파슨 러셀 테리어',
    'pekingese': '페키니즈',
    'pembroke-welsh-corgi': '웰시 코기 펨브로크',
    'peruvian-inca-orchid': '페루비안 잉카 오키드',
    'petit-basset-griffon-vendeen': '쁘띠 바셋 그리폰 방데앵',
    'pharaoh-hound': '파라오 하운드',
    'plott-hound': '플롯 하운드',
    'pointer': '포인터',
    'polish-lowland-sheepdog': '폴리시 로랜드 쉽독',
    'pomeranian': '포메라니안',
    'pont-audemer-spaniel': '퐁타우데메르 스파니엘',
    'poodle-miniature': '미니어처 푸들',
    'poodle-standard': '푸들',
    'poodle-toy': '토이 푸들',
    'porcelaine': '포슬레인',
    'portuguese-podengo': '포르투기즈 포덴고',
    'portuguese-podengo-pequeno': '포르투기즈 포덴고 페퀘노',
    'portuguese-pointer': '포르투기즈 포인터',
    'portuguese-sheepdog': '포르투기즈 쉽독',
    'portuguese-water-dog': '포르투기즈 워터 도그',
    'presa-canario': '프레사 카나리오',
    'pudelpointer': '푸델포인터',
    'pug': '퍼그',
    'puli': '풀리',
    'pumi': '푸미',
    'pyrenean-mastiff': '피레니안 마스티프',
    'pyrenean-shepherd': '피레니안 셰퍼드',
    'rafeiro-do-alentejo': '라페이로 도 알렌테조',
    'rat-terrier': '랫 테리어',
    'redbone-coonhound': '레드본 쿤하운드',
    'rhodesian-ridgeback': '로디지안 리지백',
    'romanian-carpathian-shepherd': '로마니안 카르파티안 셰퍼드',
    'romanian-mioritic-shepherd-dog': '로마니안 미오리틱 셰퍼드 도그',
    'rottweiler': '로트와일러',
    'russell-terrier': '러셀 테리어',
    'russian-toy': '러시안 토이',
    'russian-tsvetnaya-bolonka': '러시안 츠베트나야 볼롱카',
    'st-bernard': '세인트 버나드',
    'saluki': '살루키',
    'samoyed': '사모예드',
    'schapendoes': '스하펜데스',
    'schipperke': '스키퍼키',
    'scottish-deerhound': '스코티시 디어하운드',
    'scottish-terrier': '스코티시 테리어',
    'sealyham-terrier': '실리험 테리어',
    'segugio-italiano': '세구지오 이탈리아노',
    'shetland-sheepdog': '셰틀랜드 쉽독',
    'shiba-inu': '시바 이누',
    'shih-tzu': '시츄',
    'shikoku': '시코쿠',
    'siberian-husky': '시베리안 허스키',
    'silky-terrier': '실키 테리어',
    'skye-terrier': '스카이 테리어',
    'sloughi': '슬루기',
    'slovakian-wirehaired-pointer': '슬로바키안 와이어헤어드 포인터',
    'slovensky-cuvac': '슬로벤스키 쿠바츠',
    'slovensky-kopov': '슬로벤스키 코포프',
    'small-munsterlander': '스몰 뮌스터랜더',
    'smooth-fox-terrier': '스무스 폭스 테리어',
    'soft-coated-wheaten-terrier': '소프트 코티드 휘튼 테리어',
    'spanish-mastiff': '스패니시 마스티프',
    'spanish-water-dog': '스패니시 워터 도그',
    'spinone-italiano': '스피노네 이탈리아노',
    'stabyhoun': '스타비훈',
    'staffordshire-bull-terrier': '스태퍼드셔 불 테리어',
    'standard-schnauzer': '스탠다드 슈나우저',
    'sussex-spaniel': '서식스 스파니엘',
    'swedish-lapphund': '스웨디시 랩훈드',
    'swedish-vallhund': '스웨디시 발훈드',
    'taiwan-dog': '타이완 도그',
    'teddy-roosevelt-terrier': '테디 루즈벨트 테리어',
    'thai-bangkaew': '타이 방개우',
    'thai-ridgeback': '타이 리지백',
    'tibetan-mastiff': '티베탄 마스티프',
    'tibetan-spaniel': '티베탄 스파니엘',
    'tibetan-terrier': '티베탄 테리어',
    'tornjak': '토르냑',
    'tosa': '토사',
    'toy-fox-terrier': '토이 폭스 테리어',
    'transylvanian-hound': '트란실바니안 하운드',
    'treeing-tennessee-brindle': '트리잉 테네시 브린들',
    'treeing-walker-coonhound': '트리잉 워커 쿤하운드',
    'vizsla': '비즐라',
    'volpino-italiano': '볼피노 이탈리아노',
    'weimaraner': '바이마라너',
    'welsh-springer-spaniel': '웰시 스프링어 스파니엘',
    'welsh-terrier': '웰시 테리어',
    'west-highland-white-terrier': '웨스트 하이랜드 화이트 테리어',
    'wetterhoun': '베터훈',
    'whippet': '휘핏',
    'wire-fox-terrier': '와이어 폭스 테리어',
    'wirehaired-pointing-griffon': '와이어헤어드 포인팅 그리폰',
    'wirehaired-vizsla': '와이어헤어드 비즐라',
    'working-kelpie': '워킹 켈피',
    'xoloitzcuintli': '쇼로이츠퀸틀리',
    'yorkshire-terrier': '요크셔 테리어',
    'spitz': '스피츠',
    'jindo-dog': '진도견',
    'pungsan-dog': '풍산견'
}

# 추가적인 매핑
additional_mapping = {
    'pointer': '포인터',
    'shiba': '시바',
    'toy': '토이',
    'welsh-corgi-pembroke': '웰시 코기 펨브로크',
    'welsh-corgi-cardigan': '웰시 코기 카디건',
    'doberman': '도베르만',
    'terrier': '테리어',
    'retriever': '리트리버',
    'shepherd': '셰퍼드',
    'spaniel': '스파니엘',
    'hound': '하운드',
    'mastiff': '마스티프',
    'schnauzer': '슈나우저',
    'pinscher': '핀셔',
    'collie': '콜리',
    'setter': '세터'
}

# breed_mapping 확장
breed_mapping.update(additional_mapping)

try:
    # 파일 읽기
    df = pd.read_csv('/Users/hoshin/workspace/petpension/static/database/akcBreedInfo.csv')
    
    # breed_name_kor 칼럼 초기화
    df['breed_name_kor'] = ''
    
    # 매핑 적용
    for index, row in df.iterrows():
        breed_name = row['breed_name']
        
        # 정확히 일치하는 품종명이 있는 경우
        if breed_name in breed_mapping:
            df.at[index, 'breed_name_kor'] = breed_mapping[breed_name]
        else:
            # 부분 매칭 시도
            matches = []
            for eng, kor in breed_mapping.items():
                if eng in breed_name or breed_name in eng:
                    matches.append(kor)
            
            if matches:
                df.at[index, 'breed_name_kor'] = matches[0]  # 첫 번째 매칭 사용
            else:
                # 기본 영문명 그대로 사용
                df.at[index, 'breed_name_kor'] = breed_name.replace('-', ' ').title()
    
    # 결과 저장
    df.to_csv('/Users/hoshin/workspace/petpension/static/database/akcBreedInfo.csv', index=False)
    print("파일이 성공적으로 생성되었습니다: akcBreedInfo.csv")

except Exception as e:
    print(f"오류 발생: {str(e)}") 